services:
  uploadassets-app:
    environment:
      - DB_PATH
      - ASSETS_DEFAULT_USER
      - ASSETS_DEFAULT_PASS
      - ASSETS_DEFAULT_EMAIL
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uploadassets-app
    ports:
      - "8080:8087"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge
